import { signIn, signOut, useSession } from "next-auth/react";
import Head from "next/head";
import Image from "next/image";
import Timer from "~/components/timer";
import Faq from "~/components/faq";
import Footer from "~/components/footer";
import Prizes from "~/components/prizes";
import { Button, InactiveButton } from "~/components/button";
import Link from "next/link";
import { GiPaperArrow } from "react-icons/gi"

import { api } from "~/utils/api";
import next from "next";
import { useState } from "react";

export default function Home() {

  const [isRegistrationActive, setIsRegistrationActive] = useState<Boolean>(true)

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex flex-col gap-10 md:gap-20">
        
        {/* Hero Section */}

        <section className="relative h-[50vh] sm:h-[70vh] md:h-[80vh] lg:h-[90vh] bg-gradient-to-b from-primary-100 via-primary-transparent-50 via-30% to-primary-100 mt-1">
          <Image src={'/Group 2.png'} alt="Banner" className="object-cover object-center -z-10" fill/>
          <div className="mx-4 sm:mx-8 lg:mx-32 pt-28 sm:pt-28 md:pt-32 lg:pt-36 2xl:pt-44 flex flex-col items-center">
            
            {/* Contents - Hero Section */}

            <div className="flex flex-col items-center pb-10 sm:pb-8 md:pb-16 lg:pb-20 2xl:pb-32">
              <div className="font-hindi font-bold text-4xl sm:text-7xl md:text-8xl 2xl:text-9xl leading-snug sm:leading-snug md:leading-normal 2xl:leading-relaxed">Kalasangama</div>
              <div className=" text-sm sm:text-lg md:text-xl 2xl:text-4xl px-5 text-center leading-snug">Lorem ipsum dolor sit amet consectetur adipisicing elit. Reiciendis sint cupiditate aut animi sed, impedit explicabo sunt, expedita error numquam ratione, quod esse ea. Animi!</div>
            </div>
            <div className="pb-6 md:pb-8 lg:pb-12 2xl:pb-24">
              {isRegistrationActive ? <Button buttonString="Register" url="#" /> : <InactiveButton buttonString="Register" url="" />}
            </div>
          </div>
        </section>


        <section className="relative h-[25vh] max-h-40 flex items-center mx-4 sm:mx-8 lg:mx-32 justify-center">
          <div className="">
            {isRegistrationActive && <Timer setIsRegistrationActive={setIsRegistrationActive} />}
          </div>
        </section>

        {/* About the Competition */}

        <section className="relative min-h-max bg-gradient-to-b from-primary-100 via-primary-transparent-50 via-25% to-primary-100 flex items-center">
          <Image className="object-contain mix-blend-luminosity opacity-75 py-16 sm:py-28 md:py-16 -z-10" src={'/canva.png'} fill alt="mandala"></Image>

          {/* Competition Contents section */}

          <div className="mx-4 sm:mx-8 lg:mx-32 flex flex-col h-full items-center gap-5 sm:gap-16">
            <div className="flex flex-col md:flex-row items-center gap-10">
              <div className="flex flex-col gap-3">
                <div className="font-hindi text-xl sm:text-4xl md:text-4xl 2xl:text-5xl text-center md:text-left">
                  About <span className="text-secondary-100">competition</span>
                </div>
                <div className="text-xs sm:text-sm md:text-base xl:text-lg text-center md:text-left">
                  <p>Immerse yourself in the fusion of tradition and innovation as our dedicated team invites select participants to be part of this unique Yakshagana competition. This one-of-a-kind competition seamlessly integrates centuries-old storytelling with a modern approach, all while preserving the essence of this beloved folk art. Join us on this transformative journey where ancient narratives and the rich heritage of Yakshagana meets a contemporary context of technology for better experience and transparency.</p>
                </div>
              </div>
              <div className="h-40 w-40 sm:h-48 sm:w-48 lg:h-56 lg:w-56 relative shrink-0">
                <Image src={'/about.jpg'} alt="Yakshagana" fill className="object-contain object-center rounded-xl border-[5px] md:border-[6px] border-double border-secondary-100 hover:scale-105 transition duration-200 ease-linear" />
              </div>
            </div>

            {/* Rules and regulation section */}

            <div className="flex flex-col gap-3 max-w-2xl">
              <p className="font-hindi text-xl sm:text-4xl md:text-4xl 2xl:text-5xl text-center md:text-left">
                Rules & <span className="text-secondary-100">regulations</span>
              </p>
              <ul className="text-xs sm:text-sm md:text-base xl:text-lg">
                <li className="flex items-center gap-3"><GiPaperArrow className="-rotate-45 text-secondary-100 select-none" /> Lorem ipsum dolor sit amet, consectetur adipisicing elit. Aliquid, nisi!</li>
                <li className="flex items-center gap-3"><GiPaperArrow className="-rotate-45 text-secondary-100 select-none" /> LExplicabo ullam quasi similique deserunt ad voluptas consectetur dolorem</li>
                <li className="flex items-center gap-3"><GiPaperArrow className="-rotate-45 text-secondary-100 select-none" /> Obcaecati consequatur blanditiis unde voluptate eligendi ipsam oprepr enderit</li>
                <li className="flex items-center gap-3"><GiPaperArrow className="-rotate-45 text-secondary-100 select-none" /> Obcaecati consequatur blanditiis unde voluptate eligendi ipsam optio reprehenderit</li>
                <li className="flex items-center gap-3"><GiPaperArrow className="-rotate-45 text-secondary-100 select-none" /> Lorem ipsum dolor sit amet, consectetur adipisicing elit. Aliquid, nisi!</li>
                <li className="flex items-center gap-3"><GiPaperArrow className="-rotate-45 text-secondary-100 select-none" /> Lorem ipsum dolor sit amet, consectetur adipisicing elit. Aliquid, nisi!</li>
                <li className="flex items-center gap-3"><GiPaperArrow className="-rotate-45 text-secondary-100 select-none" /> Lorem ipsum dolor sit amet, consectetur adipisicing elit. Aliquid, nisi!</li>
              </ul>
            </div>
          </div>
        </section>

        {/* Prizes */}

        <section className="mx-4 sm:mx-8 lg:mx-32 flex flex-col items-center relative">
          <div className="absolute -z-10 h-48 w-48 lg:h-60 lg:w-60 bottom-[50%] right-full translate-x-[45%] lg:hidden opacity-50">
            <Image src={'/mandala.png'} fill alt='' className="object-contain opacity-70 bg-blend-luminosity" />
          </div> 
          <Prizes />
        </section>

        {/* FAQ */}

        <section className="mx-4 sm:mx-8 lg:mx-32 flex flex-col gap-3 items-center relative">
          <div className="absolute -z-10 h-48 w-48 lg:h-60 lg:w-60 bottom-full right-full hidden lg:block translate-x-[50%] lg:translate-x-0 opacity-50">
            <Image src={'/mandala.png'} fill alt='' className="object-contain opacity-70 bg-blend-luminosity" />
          </div> 
          <Faq />
        </section>
        
        <Footer />
      </main>
    </>
  );
}

// function AuthShowcase() {
//   const { data: sessionData } = useSession();

//   const { data: secretMessage } = api.example.getSecretMessage.useQuery(
//     undefined, // no input
//     { enabled: sessionData?.user !== undefined }
//   );

//   return (
//     <div className="flex flex-col items-center justify-center gap-4">
//       <p className="text-center text-2xl text-white">
//         {sessionData && <span>Logged in as {sessionData.user?.name}</span>}
//         {secretMessage && <span> - {secretMessage}</span>}
//       </p>
//       <button
//         className="rounded-full bg-white/10 px-10 py-3 font-semibold text-white no-underline transition hover:bg-white/20"
//         onClick={sessionData ? () => void signOut() : () => void signIn()}
//       >
//         {sessionData ? "Sign out" : "Sign in"}
//       </button>
//     </div>
//   );
// }
